# 应用服务web端访问配置
server:
  port: 7021
  address: 0.0.0.0
  servlet.context-path: /clownCrawler


spring:
  # 环境配置
  profiles:
    active: dev
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clown_crawler?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: ENC(5cKsQmHl2jmf2a6RDQ7jx/OC1SGe3rZqpWMg/D33Qi+99cTkByKr/cTfcuXvCmSS)
  # redis
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: ENC(Gw/PsOgVlbAjBXSSk3kWmI3oyR+LjYaRkuIlRWfjNXZl7gysn8T7Bcjmt3OVSi1G)
      lettuce:
        pool:
          max-active: 16
          max-idle: 10
          min-idle: 4
          time-between-eviction-runs: 1s

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.joker.just4fun.mybatis.entity

# jasypt加密配置
jasypt:
  encryptor:
    password: Encrypt

# slf4j日志配置
logging:
  # 配置文件位置
  config: classpath:logback-spring.xml
  # 配置级别
  level:
    # 分包配置级别，即不同的目录下可以使用不同的级别
    # 日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR，开发环境使用TRACE方便定位问题
    com.joker.just4fun.mapper: trace
