# 应用服务web端访问配置
server:
  port: 7021
  address: 0.0.0.0
  servlet.context-path: /clownCrawler

# spring相关配置
spring:
  # 环境配置
  profiles:
    active: dev
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clown_crawler?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: ENC(5cKsQmHl2jmf2a6RDQ7jx/OC1SGe3rZqpWMg/D33Qi+99cTkByKr/cTfcuXvCmSS)
  # redis
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: ENC(Gw/PsOgVlbAjBXSSk3kWmI3oyR+LjYaRkuIlRWfjNXZl7gysn8T7Bcjmt3OVSi1G)
      lettuce:
        pool:
          max-active: 16
          max-idle: 10
          min-idle: 4
          time-between-eviction-runs: 1s

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml, mapper/*Mapper.xml
  # 自动扫描并为指定包下的所有类生成别名
  type-aliases-package: com.joker.just4fun.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml, mapper/*Mapper.xml
  type-aliases-package: com.joker.just4fun.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# jasypt加密配置
jasypt:
  encryptor:
    password: Encrypt

# slf4j日志配置
logging:
  # 配置文件位置
  config: classpath:logback-spring.xml
  # 配置级别
  level:
    root: info
    # 分包配置级别，即不同的目录下可以使用不同的级别
    # 日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR，开发环境使用TRACE方便定位问题
    com.joker.just4fun.mapper: trace
#  logback:
#    rollingpolicy:
#      max-file-size: 1GB
#      max-history: 30
#      total-size-cap: 50GB

# 定制化swaggerUI
springdoc:
  swagger-ui:
    # 若要使用knife4j的UI，path: /doc.html
    path: /swagger-ui.html
    # 标签按字母顺序排序
    tags-sorter: alpha
    # 接口操作（HTTP方法与路径名）按字母顺序排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # 对API接口进行分组管理
  group-configs:
    - group: 'data_model_ctrl'
      # 接口路径匹配
      paths-to-match: '/**'
      packages-to-scan: com.joker.just4fun.controller
# swaggerUI美化工具设置
knife4j:
  # 开启增强模式
  enable: true
  # 允许在生产环境中展示API文档（设置为true，则在生产环境部署时，文档入口将会被隐藏，防止公开暴露给外部）
  production: false
  # 是否开启基础HTTP认证 (Basic Auth)
  basic:
    enable: true
    username: swagger
    password: swagger
  setting:
    # 请求和响应数据结构模型（Schemas）菜单
    swagger-model-name: 接口实体类参数列表
    enable-footer-custom: true
    footer-custom-content: Copyright © 2024 clown_crawler. All rights reserved.
    # 开启RequestMapping接口过滤，默认只显示GET
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: GET

# chromedriver相关配置
webdriver:
  driver-path: D:\\chrome\\webdriver\\chromedriver-v123-win64\\chromedriver-win64\\chromedriver.exe
  headless-mode: false